plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.sbconnect.client"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.sbconnect.client"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }

    signingConfigs {
        // Pinned debug keystore so every CI build shares one signature — new
        // builds install over the previous one without uninstalling (which
        // would otherwise reset notification access). Generated by the
        // workflow on first run and committed to the repo.
        val pinnedKeystore = rootProject.file("keystore/debug.keystore")
        if (pinnedKeystore.exists()) {
            create("pinned") {
                storeFile = pinnedKeystore
                storePassword = "sbconnect"
                keyAlias = "sbconnect"
                keyPassword = "sbconnect"
            }
        }
    }

    buildTypes {
        debug {
            // Prefer the pinned keystore; fall back to the default debug key
            // when it isn't present (e.g. a first build before CI runs).
            signingConfigs.findByName("pinned")?.let { signingConfig = it }
        }
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("com.google.android.material:material:1.12.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
}
